from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from .core import (
    CONTEXTS,
    IMPLICATIVES,
    THESIS_ROOT,
    headline_effects,
    load_empirical_inputs,
    observed_cell_means,
    prediction_frame,
)
from .m0 import run_m0
from .m1 import run_m1

def main() -> None:
    parser = argparse.ArgumentParser(description="Run the hard direct-TRY M1 model")
    parser.add_argument("--alpha", type=float, choices=(1.0,), default=1.0)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "outputs/m1",
    )
    args = parser.parse_args()

    inputs = load_empirical_inputs()
    predictions = prediction_frame(run_m1(inputs, alpha=args.alpha), inputs)
    m0_predictions = prediction_frame(run_m0(inputs, alpha=args.alpha), inputs)
    observed = observed_cell_means()

    metrics = pd.DataFrame(
        [
            {
                "model": "M0",
                "stage": "L1",
                **headline_effects(m0_predictions, "l1_p_try"),
            },
            {
                "model": "M1",
                "stage": "L0",
                **headline_effects(predictions, "l0_p_try"),
            },
            {
                "model": "M1",
                "stage": "L1",
                **headline_effects(predictions, "l1_p_try"),
            },
            {
                "model": "data",
                "stage": "observed_cell_means",
                **headline_effects(observed, "observed_p_try"),
            },
        ]
    )

    cell_comparison = predictions.merge(
        observed, on=["context", "utterance"], validate="one_to_one"
    )
    cell_comparison["l1_error"] = (
        cell_comparison["l1_p_try"] - cell_comparison["observed_p_try"]
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    predictions.to_csv(args.output_dir / "predictions.csv", index=False)
    cell_comparison.to_csv(args.output_dir / "cell_comparison.csv", index=False)
    metrics.to_csv(args.output_dir / "headline_effects.csv", index=False)

    implicative_rows = cell_comparison.loc[
        cell_comparison["utterance"].isin(IMPLICATIVES),
        ["context", "utterance", "l0_p_try", "l1_p_try", "observed_p_try"],
    ]
    report = f"""# M1 run report

Generated by `python3 -m RSA.model_comparison.run_m1`.

## Configuration

- Model: hard uniform direct lexical TRY
- Canonical alpha: `{args.alpha:g}`
- State space and world priors: identical to M0
- Costs and recursion: identical to M0
- Main naturalness ratings determine costs; TRY ratings supply evaluation targets.
- Norming items and main item x prior x QUD x utterance conditions receive equal weight.
- Inputs use full precision; alpha remains fixed at 1.

## Complete predictions

```text
{cell_comparison[['context', 'utterance', 'l0_p_try', 'l1_p_try', 'observed_p_try', 'l1_error']].to_string(index=False, float_format=lambda x: f'{x:.6f}')}
```

## Implicative diagnostic

```text
{implicative_rows.to_string(index=False, float_format=lambda x: f'{x:.6f}')}
```

## M0/M1/data headline comparison

```text
{metrics.to_string(index=False, float_format=lambda x: f'{x:.6f}')}
```

Hard M1 predicts categorical TRY for every implicative in both contexts. Its
uniform lexical condition therefore removes the implicative prior effect and
produces positive boosts for both outcome classes.
"""
    (args.output_dir / "report.md").write_text(report, encoding="utf-8")
    print(report)

if __name__ == "__main__":
    main()
