from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from .core import (
    CONTEXTS,
    THESIS_ROOT,
    headline_effects,
    load_empirical_inputs,
    observed_cell_means,
    prediction_frame,
)
from .m0 import STATES, run_m0, world_prior

def _format_mapping(values: dict[str, float]) -> str:
    return "\n".join(f"- `{name}`: {value:.6f}" for name, value in values.items())

def main() -> None:
    parser = argparse.ArgumentParser(description="Run the clean four-world M0 model")
    parser.add_argument("--alpha", type=float, choices=(1.0,), default=1.0)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "outputs/m0",
    )
    args = parser.parse_args()

    inputs = load_empirical_inputs()
    results = run_m0(inputs, alpha=args.alpha)
    predictions = prediction_frame(results, inputs)

    world_rows = []
    for context in CONTEXTS:
        for state, probability in zip(STATES, world_prior(inputs, context)):
            world_rows.append(
                {
                    "context": context,
                    "world": state.name,
                    "tried": state.tried,
                    "outcome": state.outcome,
                    "prior": probability,
                }
            )
    world_priors = pd.DataFrame(world_rows)

    metrics_rows = []
    for stage, column in (("L0", "l0_p_try"), ("L1", "l1_p_try")):
        metrics_rows.append({"stage": stage, **headline_effects(predictions, column)})
    observed = observed_cell_means()
    metrics_rows.append(
        {"stage": "observed_cell_means", **headline_effects(observed, "observed_p_try")}
    )
    metrics = pd.DataFrame(metrics_rows)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    predictions.to_csv(args.output_dir / "predictions.csv", index=False)
    world_priors.to_csv(args.output_dir / "world_priors.csv", index=False)
    metrics.to_csv(args.output_dir / "headline_effects.csv", index=False)

    report = f"""# M0 run report

Generated by `python3 -m RSA.model_comparison.run_m0`.

## Configuration

- Canonical alpha: `{args.alpha:g}`
- Norming source: `results/results_norming/norming_clean.csv`
- Naturalness source: `results/results_main/main_combined_clean.csv`
- Main naturalness ratings determine costs; TRY ratings supply evaluation targets.
- Norming items and main item x prior x QUD x utterance conditions receive equal weight.
- Inputs use full precision; alpha remains fixed at 1.

## Empirical inputs

TRY priors:

{_format_mapping(dict(inputs.try_prior))}

Completion priors:

{_format_mapping(dict(inputs.completion_prior))}

- `P(O=1|T=1)`: {inputs.response_if_try:.6f}
- `P(O=1|T=0)`: {inputs.response_without_try:.6f}

## World priors

```text
{world_priors.to_string(index=False, float_format=lambda x: f'{x:.6f}')}
```

## Naturalness costs

```text
{predictions.loc[predictions['context'].eq('high'), ['utterance', 'naturalness', 'cost']].to_string(index=False, float_format=lambda x: f'{x:.6f}')}
```

## Predictions

```text
{predictions[['context', 'utterance', 'l0_p_try', 'l1_p_try']].to_string(index=False, float_format=lambda x: f'{x:.6f}')}
```

## Headline effects

```text
{metrics.to_string(index=False, float_format=lambda x: f'{x:.6f}')}
```

M0's defining prediction is exact zero boost at both L0 and L1. Any nonzero
value beyond floating-point tolerance indicates an implementation error.
"""
    (args.output_dir / "report.md").write_text(report, encoding="utf-8")
    print(report)

if __name__ == "__main__":
    main()
